### PR TITLE
Footer fix

### PR DESCRIPTION
**Pull request by krstnmichalski**
Changed the original UCP Image into the new header as well as made some CSS changes to scale it properly.

### CODE REVIEW

**Review by Coldani3 — CHANGES_REQUESTED** [review]
Footer.js has a bunch of unused imports (also please install ESLint plugin on VSCode, it's at the top of the coding standards readme if you need instructions), which you need to get rid of, and <footer> in the return has an extra indentation (which you would have spotted if you installed the ESLint plugin). Once that's fixed it should be good though.

**Comment by P110092380** [comment]
The footer still covers some of form, until the user scrolls down, is it possible to fix this please

**Comment by krstnmichalski** [comment]
Rescaled the Footer and removed the un-used imports.

**Review by Coldani3 — APPROVED** [review]
All problems seem to be resolved, looks good.

**Pull request merged**
